### ISSUE TITLE
@focus ignored

### ISSUE THREAD

**Issue by kpturner** [TheBrainFamily/cypress-cucumber-typescript-example#3]
One of the documented "out of the box" features of https://github.com/TheBrainFamily/cypress-cucumber-example is the use of the `@focus` smart tag.   That just works without any configuration etc.

When I expanded my repo to use typescript (as per this example) then the `@focus` tags get ignored.

**Comment by lgandecki** [comment]
I just cloned this:
https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example
added another scenario, both ran, then I put @focus at one of them, only that one ran.

We would need some reproduction here before we could help you.

Please reopen if you manage to add one.

**Comment by kpturner** [comment]
Difficult to provide a example that you can clone but using this repo as example and expanding the features a little does it still work for you? I must be missing something simple.

![Screenshot 2020-07-13 at 16 23 41](https://user-images.githubusercontent.com/308646/87322569-7a079300-c525-11ea-9b95-4ed4b0a95dc3.png)
